import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

const fontPrimary = Space_Grotesk({
  variable: "--font-space-grotest",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontPrimary.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
