import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { Footer, Navbar } from "./(routes)/(root)/components";

const fontPrimary = Space_Grotesk({
  variable: "--font-space-grotest",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider

    >
      <html lang="es">
        <body
          className={`${fontPrimary.className} antialiased`}
        >
          {/* <SidebarProvider>
            <AppSidebar /> */}
          <div className="w-full flex flex-col min-h-screen">
            {/* <Navbar /> */}
            <Navbar />

            <main className="flex-1">
              {children}
            </main>
            <Footer />
          </div>
          <Toaster />
          {/* </SidebarProvider> */}
        </body>
      </html>
    </ClerkProvider >
  );
}
