import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "./(routes)/(root)/components";
import Navbar from "@/components/Shared/Navbar/Navbar";
import Footer from "@/components/Shared/Footer/Footer";

const fontPrimary = Space_Grotesk({
  variable: "--font-space-grotest",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${fontPrimary.className} antialiased`}
        >
          <SidebarProvider>
            <AppSidebar />
            <div className="w-full bg-stone-100 flex flex-col min-h-screen"> 
              <Navbar />
              <main className="flex-1">
                {children}
              </main>
              <Footer />
            </div>
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
